apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: outisa/todo-application-frontend
  newTag: f067896f94c9df74c0669f5135928f27637a194a
