apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dwk-material-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: todo-frontend-svc
          servicePort: 2345
      - path: /api
        backend:
          serviceName: todo-backend-svc
          servicePort: 2345