apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: url-secrets
  namespace: todo-app
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgC1RdHE0EoPDFR5DaDjef2dbh7Q29zBa/DOLdcDdzX366DSdfF5FTbJY1cJPMB0/h6998q2R9QH72bKlEhk+HwFNRX5kquReNnXSse3rQZp/qaHcizbvipGZcA85Ub8T9IKtQLk2zCXbCXETnHc9SEs9Jk/DjX8EEo67+tfsrd6Q9+n/WCHxkkooM9QL/GYdiUWaqYZEm5gvVcYG7Aio/bWqU2JCEujqIr8s8i+Q30+IOV1nR4QGndTVhyrmwW9kHqPsshYT8CUcVvYcrCZWQO2SMX0omDisFjkz971K3LqdqQtWxY5Is/7SabwnALGdsuT8KKQfHYptefqd6avFRcVKpmhU2S4f7AX1QA/sDcdffFSVoQaDDVeSD6b32MZv/2PeYq+CqZI7zlIwaUjggE7mbjNkO1rAztzm1VkijgH1gJr/8YfGNxj3PDE8p7CV/vZpL6PyTDFJpcDowARb/G2sLjr9w7gxWe3c7hRjN8xCPNcKF6+Wk+fO/gSy8MV7ZLAe+SlOWrTBtT+gzT2GL9xSlaU5i0Lcm4MkwkK7oTanAtJSRCtVtgDSe5JKCJLSVdusIaiPW4b0gjnpFhIQUyR5dwZg/Y4cbd50Yn2g8ZcSwj2a1yZ0daC5XXAc6apWyvxl0KO7Dk2frsu9hvpQAEdzwrLCgeLOBt9TxY3i18FxwF27S6FPUvRo59dxzSQFqMiDjUPITEssaqxXVIsewv61CpkB/svgCXZSAK6Qo3J1/kNtmz07k8w3sYxZQzcnp5OTm7nHn7pV2sjwYFzGqM6jvgPKl6Ymi9753816P7K0Nq1RXbZAfQinW9lL6IcT7EBys7AMR87LRFcRN/dH7Z6kMCuxWTUo2g=
    NATS_URL: AgAYrS+E9I3nrL36aVsbKGKZX9wTHvJht7HC1IDSVlNkHqSNNwjcrzczppajgC857+lCbq/bBjk00L9rmgCWtZhB8ok58BOUn1/27qUXP7Zy7sVzEvTVi433jueNi9LScxPJa8P2oLGoznAOsTotpf3xaKCOOOJ9j0xHc/tCIIeX/YuZVcPRL5LSB30cQ1MoRK/k7/GQ4cI1n5m3cWlHpjpkyFNzaFY7HurZ8OgbNx4kZiQxnpkuuBVhvbVAJcCp0c55Jzs/NlghCU9piehV5IzH8FNRXSJfDdp6bCeoYj9IDOykNG/buNLGwbrKPzmoFx92DtvHOzONn9ydISIWVYYH/7FsY0OTNrTL8e4QWmL8XmBjP8ZsRXdRs8ONAqphcFc0AvKJs7jBLKF/hcPp84DuSBvaktEkVeXoh5XRp6UXgEs+AjMY+9al1cFLecmXMYn0vAvqsAUVzFOgafHXglAfc5PUFWDz7kk6bfP2ugs+tZJIK/lmRjnJtIg1fq+g3FXxcIpL5MdjkHsdsSvr003B4/dOdI93WE/YG7U1GSRuSk3UJcwUrrX0SSU490+Epp/ELjQDt5TrntGClnofssPvfb2BTkGG5Vr9ymQc3FP7brOa7qTdZnbrpYgK8HJoAzAUHwsFo9An09aEeCF+7tmG39Y5RmsoJ70iCyTJWQfAV5sT0WfXKPBLZuK26pX6U+Bey2VhkvyML09uJi8vk73G1MNs
  template:
    metadata:
      creationTimestamp: null
      name: url-secrets
      namespace: todo-app

