apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo
          image: outisa/todo-application:c082d9bb3cf57b7943be072d54d6d2df9adabecd
          volumeMounts:
            - mountPath: /app/backend/files
              name: shared-image
