apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo
          image: outisa/todo-application:8fe016ecde4949b1c8ca8f31fa62fe34eb390bf8
          volumeMounts:
            - mountPath: /app/files
              name: shared-image
