apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- cronjob.yaml
- ingress.yaml
- service.yaml
- stateful.yaml
- sealedsecret.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: outisa/todo-application-backend
  newTag: 0bda324a97a6d2b5c080a327dd4c66c734b98dfb
