apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- cronjob.yaml
- ingress.yaml
- service.yaml
- stateful.yaml
- sealedsecret.yaml
- ../../broadcaster/manifests/sealedsecret.yaml
- ../../broadcaster/manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: outisa/todo-application-backend
  newTag: c130f294e099e30adb19409cfa080205b3a4102e
