apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- cronjob.yaml
- ingress.yaml
- service.yaml
- stateful.yaml
- sealedsecret.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: outisa/todo-application-backend
  newTag: fe144656f1f336614da65e0e890d6710ba7a51b5
