apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE1
          resources:
            limits:
              cpu: "150m"
              memory: "25Mi"
          volumeMounts:
            - mountPath: /app/backend/files
              name: shared-image
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-todos
                key: POSTGRES_PASSWORD    
