apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-backend
          image: outisa/todo-application-backend:f1418cb94b5427e8ce7701122c696566bb4c22aa
          volumeMounts:
            - mountPath: /app/backend/files
              name: shared-image
