apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoapp-namespace
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-backend
          image: outisa/todo-application-backend:c76ae2a94734413eca51f2680ab2a4130ca049d3
          volumeMounts:
            - mountPath: /app/backend/files
              name: shared-image
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-todos
                key: POSTGRES_PASSWORD    
