apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-backend
          image: outisa/todo-application-backend:d6163d11039fd9cb5f8d4c5e2c96d24be3cf4f79
          volumeMounts:
            - mountPath: /app/backend/files
              name: shared-image
