apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend-hpa
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend-dep
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
