apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-backend-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: todo-backend-svc
          servicePort: 80