apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todoapp-namespace
  name: image-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi