apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials-todos
  namespace: todoapp-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAj36EtUCowuQdbjtluVHKg62ScpdP5gc5bneEP+s5XNtjGNsUa2GdESwNjE519wlOoXeQwGUe5x+CYHD7C6lThkrQNbb5DdEml7zdJnZ+kXNonxI5uWvT3iOG0YQJVsGpGwti8bYCuVTNJ04JSdlzdEi+Zy0rk7KgRkLDYv173b0NUxZ3JN8bpSnglqKlqNnVgKZMP/LbB060aBJaPWhqksXw99PBqAkfE/I9mUIRUEsGvzN+kcZL6eKsQCaPUhXBJVNXwoY3xwb4zKBgWqYhF8RMGiaZCE8OjnMnSPBSlsZGcufhcZiN+jkuyr0urPKmcigJklyzH3sM66xWkp5wNdDBsZWBLgvHN2PRaQV+MblvW4JudCWugwjc1IL1PntexVgJu/rXoMSaDWUPCbw5FlzwuNIAlD30+8cbfRjE+YudTiJ8DjvRLLUL/cG3UjGwUS1exFP9XUWXGHJjguw1ancn5DCJMvEpNM0RERCcaw1CrJz97eQx84xdgim0X1MQYK/CL7+9KEwRB96jro4GhoJdAeD2JXQweF0wkpZa16Uyu1mKOthrozMZNeoFy1rUMPU9SI81gB9N0ALHJ4yXezhjHA/HQYYc9XVpkl4sYZ3xtA/pHcnE5yAN+65IY7FIQa77yuG942/7gEG/+ZTN4a9LnHm2AJUmAYXNeAxHRuvs7GntcAOQkhQ6mNNVjlBQ3G1qOytPS
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials-todos
      namespace: todoapp-namespace

