apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: mainapp-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCVl22TO0zyzwsZMHH2wjwqZfxzwZJ8+65Y0Z2JNXLPLlX/gC7ONLNrH+8o3KUen9L+YqVdxK94O8webF+emu/Coy5uVj7oOfxXitz0FL/Cim8MwAJXy8+vuK+e8JBhBAfDL9XoqYW/KeDkvo7WxrVLOh2NZrtHbV/9qibzxa3DpmapcULN6qip+1bc65SdbjPnUgOl1/VRtJcRtZDm0P0re4THAuBYAVMZTBTioKwCTuniFeYgOOHgS26TbFfVwizzx0qRavvWy/mv18aDzAkAlcMBoZdhAxJEZDgReBbCrecoKUXlHHN3QOQOT6zk21VwQD6inKac799RY4NGvGRWRfiztDKggv2zxBmT6lq4Ei0qEEAmSaeYgRzXgc876jjkGtqg9d6Xc0CbkfGl/yihJ78C7VuqqBhLnX3CAFJ+PrJYSVnht9emX5lCnGXwocWdCoP60EqmjyXXmcbyUWFYvQveSKxWcv45tBpGl7dcU0KnSc2upVwn0GmDJdZ6Y50kGkc8SEOkV8W30TvWNLk1Qxcp/U/nlv2JuuAJlXs5PDZE8o3+rAPr0CHD9reelxQc4tm6ZjrOlfbn0C8IOED32THfYTPOHn0EI7oCHO3HnZ9qQTPRbTa2AstWif/TV+PiLMBUEF/s3RqBnnjrtBYNVzcmE7mstEtwXgFvDqKVenu0ldgpGznySPlJ1S90Gc+ycBwrut7P
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: mainapp-namespace

