apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials-todos
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCpF5Bv3dyTboCGNImW1AaxTI1PJbaeCH/F7GgWlS4COYaT2Hg1lQZkGx3reqE9tzJrwEp976OTxnnmh4Sh4z8JbHL0wyJnTxKS7xay430DQok8N/vS7CqQn8l9hIxQsN7KbY0kpPUfZg5KQEXL/DsIGN8pyQZi2Hs4vvmSb8Qi2ab5/TNnvmALJCyvFRLag4Ft6Tra5NaguxyspDr7NMg7siBQSJY7uEKtxA54LOJD+23MaQo++sF2VF8el9MpDyzFBo9YGTYVtkeGkmOSpZ0h44C4FYo2vH7QG2BsvSQzTcZMVe1sZiM9uolUUme5qnEPBmMRdUFEsghj7W/SkoUigkfljEA5ODnoRyhov41+lKxIdg7eREHgRbEEyyI+bHx3Yju9a/u+j2rgheIDN5rkrr14lJUtE9pN8nXCXk8QaOaNdNjOh7jduO1cqCWYFU60drA2ISF20SSL16qGX7ZCPqcBdYQ+CW9TLnsaIbf/et7Ger66oc6+rinUegM9/4MXx5/oHbZW2SA1t4oFK/y7GewsOhYHLE+Nw0VeGL1F9UAdctcrXuV+jjNIDBKK5PfqOzg2Z1Qeft4GXexyyCErdFed3yVr1XSnftYGXfq+bl4IcuqrXuxuxMIBKCa5I5tbflQt1ch2G6UB+38LMQvp658mJ6PR2Eo3oFCV5z5d5u/PN4/RydwVg3WZgSVNb0EGPt2ehgko
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials-todos
      namespace: default

