apiVersion: v1
kind: Service
metadata:
  namespace: todoapp-namespace
  name: todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - name: local
      port: 2345
      protocol: TCP
      targetPort: 3001
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001  