apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001  